using NetCore.Oracle.DataAccess;
using Temp_BE.Application.Interface.Repositories;
using Temp_BE.Base.Databases;
using Temp_BE.Domain.Common;
using Temp_BE.Domain.DTOs;
using Temp_BE.Domain.Requests;
using Temp_BE.Infrastructure.Persistence.DbMappings;
using static NetCore.Oracle.DataAccess.LinqExtension;

namespace Temp_BE.Infrastructure.Persistence.Repositories
{
    public class SanPhamRepository : ISanPhamRepository
    {
        private readonly IDbSession<DbQLBH> _db;
        private readonly ILogger<SanPhamRepository> _logger;


        public SanPhamRepository(IDbSession<DbQLBH> db, ILogger<SanPhamRepository> logger)
        {
            _db = db;
            _logger = logger;
        }

        public async Task<PagedResult<SanPhamDto>> GetPagedListAsync(SanPhamFilterRequest req, CancellationToken ct = default)
        {


            var keyword = string.IsNullOrWhiteSpace(req.Keyword) ? null : req.Keyword.Trim();
            var skip = (req.PageIndex - 1) * req.PageSize;

            var countRows = await _db.ToListAsync(
                 from x in _db.GetAll<SanPhamDb>()
                 where (x.TenSp.Contains(keyword) || x.MaSp.Contains(keyword))
                     .IfGenerateQuery(keyword != null)
                 select new { total = 1.Count() },
                isMapping: false, ct: ct);

            var total = (long)(countRows.FirstOrDefault()?.total ?? 0);
            var filtered =
            from x in _db.GetAll<SanPhamDb>()
            where (x.TenSp.Contains(keyword) || x.MaSp.Contains(keyword) || x.GiaBan <= req.MaxPrice || x.GiaBan >= req.MinPrice)
                .IfGenerateQuery(keyword != null)
            select x;
            var numberedQuery =
                from x in filtered
                select new
                {
                    RowNumber = x.RowNumber(() => x.MaSp),
                    x.MaSp,
                    x.TenSp,
                    x.GiaBan,
                    x.SoLuong,
                    x.TrangThai
                };

            var pageQuery =
                from a in numberedQuery
                where a.RowNumber > skip && a.RowNumber <= skip + req.PageSize
                orderby a.RowNumber
                select a;

            var rows = await _db.ToListAsync(pageQuery, isMapping: false, ct: ct);

            return new PagedResult<SanPhamDto>(
                rows.Select(x => new SanPhamDto
                {
                    MaSp = x.MaSp,
                    TenSp = x.TenSp,
                    GiaBan = x.GiaBan,
                    SoLuong = x.SoLuong,
                    TrangThai = x.TrangThai
                }).ToList(),
                total
            );
        }
        public async Task<SanPhamDto?> GetByMaSpAsync(string maSp)
        {
            return await _db.FirstOrDefaultAsync<SanPhamDto>(
                from a in _db.GetAll<SanPhamDb>()
                where a.MaSp == maSp
                select new
                {
                    MaSp = a.MaSp,
                    TenSp = a.TenSp,
                    GiaBan = a.GiaBan,
                    SoLuong = a.SoLuong,
                    TrangThai = a.TrangThai
                },
                isMapping: false
            );
        }

        public async Task<SanPhamDto> CreateAsync(CreateSanPhamRequest req)
        {
            string autoGeneratedMaSp = $"SP{DateTime.Now:yyMMddHHmmss}";
            var entity = new SanPhamDb
            {
                MaSp = autoGeneratedMaSp,
                TenSp = req.TenSp,
                GiaBan = req.GiaBan,
                SoLuong = req.SoLuong,
                TrangThai = req.TrangThai
            };

            await _db.InsertAsync(entity);
            return new SanPhamDto
            {
                MaSp = entity.MaSp,
                TenSp = entity.TenSp,
                GiaBan = entity.GiaBan,
                SoLuong = entity.SoLuong,
                TrangThai = entity.TrangThai
            };
        }

        public async Task<SanPhamDto?> UpdateAsync(string maSp, UpdateSanPhamRequest req)
        {
            var entity = await _db.FirstOrDefaultAsync<SanPhamDb>(
                from a in _db.GetAll<SanPhamDb>()
                where a.MaSp == maSp
                select a
            );

            if (entity == null) return null;

            entity.TenSp = req.TenSp;
            entity.GiaBan = req.GiaBan;
            entity.SoLuong = req.SoLuong;
            entity.TrangThai = req.TrangThai;

            await _db.UpdateAsync(entity);

            return new SanPhamDto
            {
                MaSp = entity.MaSp,
                TenSp = entity.TenSp,
                GiaBan = entity.GiaBan,
                SoLuong = entity.SoLuong,
                TrangThai = entity.TrangThai
            };
        }

        public async Task<bool> DeleteAsync(string maSp)
        {
            await _db.DeleteWithClauseAsync<SanPhamDb>(x => x.MaSp == maSp);
            return true;
        }

        public async Task<bool> ExistsAsync(string maSp)
        {
            var result = await _db.ToListAsync((from a in _db.GetAll<SanPhamDb>()
                                                where a.MaSp == maSp
                                                select a.MaSp).Take(1));
            return result.Count > 0;
        }

        public async Task DeductStockAsync(string maSp, decimal soLuong)
        {
            var entity = await _db.FirstOrDefaultAsync<SanPhamDb>(
                from a in _db.GetAll<SanPhamDb>()
                where a.MaSp == maSp
                select a
            );
            if (entity == null) return;

            entity.SoLuong = (entity.SoLuong ?? 0) - soLuong;
            await _db.UpdateAsync(entity);
        }
    }
}