<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Temp-BE.Application\Temp-BE.Application.csproj" />
    <ProjectReference Include="..\Temp-BE.Domain\Temp-BE.Domain.csproj" />
    <ProjectReference Include="..\Temp-BE.Base\Temp-BE.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="NetCore.Oracle.DataAccess" Version="26.9.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Temp_BE.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
