using NetCore.Oracle.DataAccess;
using Temp_BE.Application.Interface.Repositories;
using Temp_BE.Base.Databases;
using Temp_BE.Domain.Common;
using Temp_BE.Domain.DTOs;
using Temp_BE.Infrastructure.Persistence.DbMappings;

namespace Temp_BE.Infrastructure.Persistence.Repositories
{
    public class SanPhamRepository : ISanPhamRepository
    {
        private readonly IDbSession<DbQLBH> _db;

        public SanPhamRepository(IDbSession<DbQLBH> db)
        {
            _db = db;
        }

        public async Task<PagedResult<SanPhamDto>> GetPagedListAsync(SanPhamFilterRequest request)
        {
            var query = from a in _db.GetAll<SanPhamDb>() select a;

            if (!string.IsNullOrWhiteSpace(request.Keyword))
            {
                var keyword = request.Keyword.Trim().ToUpper();
                query = query.Where(x => x.TenSp.ToUpper().Contains(keyword) || x.MaSp.ToUpper().Contains(keyword));
            }
            if (request.MinPrice.HasValue)
            {
                query = query.Where(x => x.GiaBan >= request.MinPrice.Value);
            }
            if (request.MaxPrice.HasValue)
            {
                query = query.Where(x => x.GiaBan <= request.MaxPrice.Value);
            }

            if (request.TrangThai.HasValue)
            {
                query = query.Where(x => x.TrangThai == request.TrangThai.Value);
            }

            var allItems = await _db.ToListAsync<SanPhamDto>(
                from a in query
                select new
                {
                    MaSp = a.MaSp,
                    TenSp = a.TenSp,
                    GiaBan = a.GiaBan,
                    SoLuong = a.SoLuong,
                    TrangThai = a.TrangThai
                },
                isMapping: false
            );

            if (!string.IsNullOrWhiteSpace(request.SortBy) && request.SortBy.Equals("GiaBan", StringComparison.OrdinalIgnoreCase))
            {
                allItems = request.IsAscending
                    ? allItems.OrderBy(x => x.GiaBan).ToList()
                    : allItems.OrderByDescending(x => x.GiaBan).ToList();
            }
            else if (!string.IsNullOrWhiteSpace(request.SortBy) && request.SortBy.Equals("TenSp", StringComparison.OrdinalIgnoreCase))
            {
                allItems = request.IsAscending
                    ? allItems.OrderBy(x => x.TenSp).ToList()
                    : allItems.OrderByDescending(x => x.TenSp).ToList();
            }
            else
            {
                allItems = request.IsAscending
                    ? allItems.OrderBy(x => x.MaSp).ToList()
                    : allItems.OrderByDescending(x => x.MaSp).ToList();
            }

            int totalCount = allItems.Count;

            int skip = (request.PageIndex - 1) * request.PageSize;
            var pagedItems = allItems.Skip(skip).Take(request.PageSize).ToList();

            return new PagedResult<SanPhamDto>(pagedItems, totalCount, request.PageIndex, request.PageSize);
        }

        public async Task<SanPhamDto?> GetByMaSpAsync(string maSp)
        {
            return await _db.FirstOrDefaultAsync<SanPhamDto>(
                from a in _db.GetAll<SanPhamDb>()
                where a.MaSp == maSp
                select new
                {
                    MaSp = a.MaSp,
                    TenSp = a.TenSp,
                    GiaBan = a.GiaBan,
                    SoLuong = a.SoLuong,
                    TrangThai = a.TrangThai
                },
                isMapping: false
            );
        }

        public async Task<SanPhamDto> CreateAsync(CreateSanPhamDto dto)
        {
            string autoGeneratedMaSp = $"SP{DateTime.Now:yyMMddHHmmss}";
            var entity = new SanPhamDb
            {
                MaSp = autoGeneratedMaSp,
                TenSp = dto.TenSp,
                GiaBan = dto.GiaBan,
                SoLuong = dto.SoLuong,
                TrangThai = dto.TrangThai
            };

            await _db.InsertAsync(entity);
            return new SanPhamDto
            {
                MaSp = entity.MaSp,
                TenSp = entity.TenSp,
                GiaBan = entity.GiaBan,
                SoLuong = entity.SoLuong,
                TrangThai = entity.TrangThai
            };
        }
        public async Task<SanPhamDto?> UpdateAsync(string maSp, UpdateSanPhamDto dto)
        {
            var entity = await _db.FirstOrDefaultAsync<SanPhamDb>(
                from a in _db.GetAll<SanPhamDb>()
                where a.MaSp == maSp
                select a
            );

            if (entity == null) return null;

            entity.TenSp = dto.TenSp;
            entity.GiaBan = dto.GiaBan;
            entity.SoLuong = dto.SoLuong;
            entity.TrangThai = dto.TrangThai;

            await _db.UpdateAsync(entity);

            return new SanPhamDto
            {
                MaSp = entity.MaSp,
                TenSp = entity.TenSp,
                GiaBan = entity.GiaBan,
                SoLuong = entity.SoLuong,
                TrangThai = entity.TrangThai
            };
        }
        public async Task<bool> DeleteAsync(string maSp)
        {
            await _db.DeleteWithClauseAsync<SanPhamDb>(x => x.MaSp == maSp);
            return true;
        }

        public async Task<bool> ExistsAsync(string maSp)
        {
            var result = await _db.ToListAsync((from a in _db.GetAll<SanPhamDb>()
                                                where a.MaSp == maSp
                                                select a.MaSp).Take(1));
            return result.Count > 0;
        }
    }
}